[build-system]
requires = ["maturin>=1.9.4,<1.10.0"]
build-backend = "maturin"

[project]
name = "rust_stdf_helper"
version = "0.3.0"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


